name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust this based on your Next.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Export the static site
        run: npm run export

      - name: Upload files via FTP to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          ftp-port: ${{ secrets.FTP_PORT }}
          local-dir: ./out  # Path to your exported Next.js build
          remote-dir: /public_html  # Adjust based on where you want to deploy the files
